// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(BnBDbContext))]
    [Migration("20210606111530_CorrectionsRoomAndBnBAndContact")]
    partial class CorrectionsRoomAndBnBAndContact
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AmenityBnB", b =>
                {
                    b.Property<int>("AmenitiesAmenityId")
                        .HasColumnType("int");

                    b.Property<int>("BnBsBnBId")
                        .HasColumnType("int");

                    b.HasKey("AmenitiesAmenityId", "BnBsBnBId");

                    b.HasIndex("BnBsBnBId");

                    b.ToTable("AmenityBnB");

                    b.HasData(
                        new
                        {
                            AmenitiesAmenityId = 1,
                            BnBsBnBId = 1
                        },
                        new
                        {
                            AmenitiesAmenityId = 1,
                            BnBsBnBId = 5
                        },
                        new
                        {
                            AmenitiesAmenityId = 1,
                            BnBsBnBId = 3
                        },
                        new
                        {
                            AmenitiesAmenityId = 1,
                            BnBsBnBId = 4
                        },
                        new
                        {
                            AmenitiesAmenityId = 2,
                            BnBsBnBId = 3
                        },
                        new
                        {
                            AmenitiesAmenityId = 3,
                            BnBsBnBId = 1
                        },
                        new
                        {
                            AmenitiesAmenityId = 3,
                            BnBsBnBId = 3
                        },
                        new
                        {
                            AmenitiesAmenityId = 4,
                            BnBsBnBId = 1
                        },
                        new
                        {
                            AmenitiesAmenityId = 4,
                            BnBsBnBId = 3
                        },
                        new
                        {
                            AmenitiesAmenityId = 4,
                            BnBsBnBId = 5
                        },
                        new
                        {
                            AmenitiesAmenityId = 5,
                            BnBsBnBId = 2
                        },
                        new
                        {
                            AmenitiesAmenityId = 5,
                            BnBsBnBId = 4
                        });
                });

            modelBuilder.Entity("AmenityRoom", b =>
                {
                    b.Property<int>("AmenitiesAmenityId")
                        .HasColumnType("int");

                    b.Property<int>("RoomsRoomId")
                        .HasColumnType("int");

                    b.HasKey("AmenitiesAmenityId", "RoomsRoomId");

                    b.HasIndex("RoomsRoomId");

                    b.ToTable("AmenityRoom");

                    b.HasData(
                        new
                        {
                            AmenitiesAmenityId = 1,
                            RoomsRoomId = 1
                        },
                        new
                        {
                            AmenitiesAmenityId = 1,
                            RoomsRoomId = 2
                        },
                        new
                        {
                            AmenitiesAmenityId = 1,
                            RoomsRoomId = 3
                        },
                        new
                        {
                            AmenitiesAmenityId = 1,
                            RoomsRoomId = 7
                        },
                        new
                        {
                            AmenitiesAmenityId = 1,
                            RoomsRoomId = 8
                        },
                        new
                        {
                            AmenitiesAmenityId = 1,
                            RoomsRoomId = 9
                        },
                        new
                        {
                            AmenitiesAmenityId = 1,
                            RoomsRoomId = 10
                        },
                        new
                        {
                            AmenitiesAmenityId = 1,
                            RoomsRoomId = 11
                        },
                        new
                        {
                            AmenitiesAmenityId = 1,
                            RoomsRoomId = 12
                        },
                        new
                        {
                            AmenitiesAmenityId = 3,
                            RoomsRoomId = 7
                        },
                        new
                        {
                            AmenitiesAmenityId = 3,
                            RoomsRoomId = 10
                        },
                        new
                        {
                            AmenitiesAmenityId = 3,
                            RoomsRoomId = 11
                        },
                        new
                        {
                            AmenitiesAmenityId = 4,
                            RoomsRoomId = 11
                        },
                        new
                        {
                            AmenitiesAmenityId = 4,
                            RoomsRoomId = 5
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AmenityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmenityIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmenityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AmenityRate")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("AmenityId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            AmenityDescription = "We don't charge you for using our wifi.",
                            AmenityName = "free wifi",
                            AmenityRate = 0.0,
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 383, DateTimeKind.Local).AddTicks(1451),
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AmenityId = 2,
                            AmenityDescription = "We don't swim in your toilet, so please don't pee in our pool.",
                            AmenityName = "pool",
                            AmenityRate = 20.0,
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 385, DateTimeKind.Local).AddTicks(8778),
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AmenityId = 3,
                            AmenityDescription = "For people who like to sweat",
                            AmenityName = "sauna",
                            AmenityRate = 25.0,
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 385, DateTimeKind.Local).AddTicks(8827),
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AmenityId = 4,
                            AmenityDescription = "The relaxing kind, not the Japanese maffia.",
                            AmenityName = "jacuzzi",
                            AmenityRate = 33.0,
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 385, DateTimeKind.Local).AddTicks(8832),
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AmenityId = 5,
                            AmenityDescription = "For rainy days.",
                            AmenityName = "pingpongtafelke",
                            AmenityRate = 0.0,
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 385, DateTimeKind.Local).AddTicks(8835),
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DataAccess.Data.BnB", b =>
                {
                    b.Property<int>("BnBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankAccountNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BnBDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BnBEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BnBName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BnBPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VATnr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BnBId");

                    b.ToTable("BnBs");

                    b.HasData(
                        new
                        {
                            BnBId = 1,
                            BankAccountNr = "BE59889nogmeerdiefstal",
                            BnBDetails = "details hier",
                            BnBEmail = "jos@mail",
                            BnBName = "Boerenhol",
                            BnBPhone = "0123",
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 388, DateTimeKind.Local).AddTicks(1774),
                            HouseNumber = "4",
                            Municipality = "Reningelst",
                            NameOwner = "Jos",
                            PostalCode = 8970,
                            Province = "West-Vlaanderen",
                            StreetName = "Driegoenstraat",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VATnr = "BE3524874diefstal"
                        },
                        new
                        {
                            BnBId = 2,
                            BankAccountNr = "BE59654nogmeerdiefstal",
                            BnBDetails = "details hier",
                            BnBEmail = "jos@mail",
                            BnBName = "Boskant",
                            BnBPhone = "0123",
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 388, DateTimeKind.Local).AddTicks(7391),
                            HouseNumber = "8",
                            Municipality = "Helchteren",
                            NameOwner = "Jos",
                            PostalCode = 3530,
                            Province = "Limburg",
                            StreetName = "Terrillstraat",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VATnr = "BE3526654diefstal"
                        });
                });

            modelBuilder.Entity("DataAccess.Data.BnBImage", b =>
                {
                    b.Property<int>("BnBImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BnBId")
                        .HasColumnType("int");

                    b.Property<string>("BnBImageSourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("BnBImageId");

                    b.HasIndex("BnBId");

                    b.ToTable("BnBImages");
                });

            modelBuilder.Entity("DataAccess.Data.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "9e7e9cd1-6ca4-4548-9bba-b31f8e2d5e78",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "50679962-05a1-43b7-a225-4f6ebc552950",
                            ContactName = "Arthur Blanckaert",
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 387, DateTimeKind.Local).AddTicks(4212),
                            Email = "tuur@zanger.be",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumber = "016/026.754",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2145751b-d0d1-4a95-95c3-8e274500abe4",
                            TwoFactorEnabled = false,
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "a617f3e8-12d7-4c38-94a2-e65d7fdc5200",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a29a4a3c-ea50-44fd-b294-6fcba5ea8726",
                            ContactName = "Eddy Wally",
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 387, DateTimeKind.Local).AddTicks(8056),
                            Email = "wally@zanger.be",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumber = "09/657.237",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c4537204-f760-4ebf-8d84-5214614f3f82",
                            TwoFactorEnabled = false,
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "de31b137-ba8c-409b-b4ef-2df5922a9de0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb1345e8-63ee-4a0a-b4ca-7dfd71370da7",
                            ContactName = "Rocking Moustache",
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 387, DateTimeKind.Local).AddTicks(8085),
                            Email = "moustache@zanger.be",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumber = "016/981.247",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "83a090af-4952-4e56-82b6-6eb6e68f7bdb",
                            TwoFactorEnabled = false,
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "059d9ac4-8f00-4652-a991-066bd470b2f2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c93524d7-5590-418f-b280-06d98ef0ff34",
                            ContactName = "Koen Crucke",
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 387, DateTimeKind.Local).AddTicks(8105),
                            Email = "crucke@zanger.be",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumber = "03/026.754",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f3b8fff-d596-4aa1-9db7-e44bcc8bf1a0",
                            TwoFactorEnabled = false,
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "e64d13b7-0202-4820-899a-db46a9a1213a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fcdc875e-101a-44d7-82c6-610a0230e10f",
                            ContactName = "Bart Kaëll",
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 387, DateTimeKind.Local).AddTicks(8113),
                            Email = "kajell@zanger.be",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b4168dc6-b41c-463c-b639-3edd5e15bb94",
                            TwoFactorEnabled = false,
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "5af343e7-29e2-484b-979c-9463f610b16a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "79605074-f49b-4a68-8ba2-0686d91b850e",
                            ContactName = "Luk Steeno",
                            CreatedOn = new DateTime(2021, 6, 6, 13, 15, 29, 387, DateTimeKind.Local).AddTicks(8121),
                            Email = "steeno@zanger.be",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "37013e02-c670-4ed1-8ab0-bf4c540f994b",
                            TwoFactorEnabled = false,
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DataAccess.Data.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BnBId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("bit");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("RoomDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomSize")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RoomId");

                    b.HasIndex("BnBId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            BnBId = 1,
                            CreatedDate = new DateTime(2021, 6, 6, 13, 15, 29, 389, DateTimeKind.Local).AddTicks(1819),
                            Occupancy = 2,
                            PetsAllowed = false,
                            Rate = 105.0,
                            RoomDetails = "details hier",
                            RoomName = "Hommelkamer",
                            RoomSize = 36,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoomId = 2,
                            BnBId = 1,
                            CreatedDate = new DateTime(2021, 6, 6, 13, 15, 29, 389, DateTimeKind.Local).AddTicks(4873),
                            Occupancy = 2,
                            PetsAllowed = false,
                            Rate = 100.0,
                            RoomDetails = "details hier",
                            RoomName = "Rozenkamer",
                            RoomSize = 28,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoomId = 3,
                            BnBId = 1,
                            CreatedDate = new DateTime(2021, 6, 6, 13, 15, 29, 389, DateTimeKind.Local).AddTicks(4887),
                            Occupancy = 3,
                            PetsAllowed = false,
                            Rate = 115.0,
                            RoomDetails = "details hier",
                            RoomName = "Wespenkamer",
                            RoomSize = 46,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoomId = 4,
                            BnBId = 2,
                            CreatedDate = new DateTime(2021, 6, 6, 13, 15, 29, 389, DateTimeKind.Local).AddTicks(4890),
                            Occupancy = 1,
                            PetsAllowed = false,
                            Rate = 97.0,
                            RoomDetails = "details hier",
                            RoomName = "Bijenkamer",
                            RoomSize = 35,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoomId = 5,
                            BnBId = 2,
                            CreatedDate = new DateTime(2021, 6, 6, 13, 15, 29, 389, DateTimeKind.Local).AddTicks(4893),
                            Occupancy = 4,
                            PetsAllowed = false,
                            Rate = 124.0,
                            RoomDetails = "details hier",
                            RoomName = "Mierenkamer",
                            RoomSize = 29,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoomId = 6,
                            BnBId = 2,
                            CreatedDate = new DateTime(2021, 6, 6, 13, 15, 29, 389, DateTimeKind.Local).AddTicks(4896),
                            Occupancy = 2,
                            PetsAllowed = false,
                            Rate = 116.0,
                            RoomDetails = "details hier",
                            RoomName = "Duizendpootkamer",
                            RoomSize = 26,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DataAccess.Data.RoomImage", b =>
                {
                    b.Property<int>("RoomImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("RoomImageSourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomImageId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages");
                });

            modelBuilder.Entity("DataAccess.Data.RoomOrderDetails", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActualCheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ActualCheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaymentSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("StripeSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomOrderDetails");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AmenityBnB", b =>
                {
                    b.HasOne("DataAccess.Data.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesAmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.BnB", null)
                        .WithMany()
                        .HasForeignKey("BnBsBnBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AmenityRoom", b =>
                {
                    b.HasOne("DataAccess.Data.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesAmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Data.BnBImage", b =>
                {
                    b.HasOne("DataAccess.Data.BnB", "BnB")
                        .WithMany("BnBImages")
                        .HasForeignKey("BnBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BnB");
                });

            modelBuilder.Entity("DataAccess.Data.Room", b =>
                {
                    b.HasOne("DataAccess.Data.BnB", "BnB")
                        .WithMany("Rooms")
                        .HasForeignKey("BnBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BnB");
                });

            modelBuilder.Entity("DataAccess.Data.RoomImage", b =>
                {
                    b.HasOne("DataAccess.Data.Room", "Room")
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DataAccess.Data.RoomOrderDetails", b =>
                {
                    b.HasOne("DataAccess.Data.Room", "BnBRoom")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BnBRoom");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccess.Data.Contact", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccess.Data.Contact", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Data.Contact", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccess.Data.Contact", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Data.BnB", b =>
                {
                    b.Navigation("BnBImages");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DataAccess.Data.Room", b =>
                {
                    b.Navigation("RoomImages");
                });
#pragma warning restore 612, 618
        }
    }
}
